# Data Preprocessing Tools

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_excel('/content/Data.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


In [3]:
print(X)

[['France' 48.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 15.0 54000.0]
 ['Spain' 38.0 20000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 40000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [8]:
print(X)

[[1.0 0.0 0.0 48.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 15.0 54000.0]
 [0.0 0.0 1.0 38.0 20000.0]
 [0.0 1.0 0.0 40.0 57888.88888888889]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 37.55555555555556 40000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
#X = ct.fit_transform(X)

In [9]:
print(X)

[[1.0 0.0 0.0 48.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 15.0 54000.0]
 [0.0 0.0 1.0 38.0 20000.0]
 [0.0 1.0 0.0 40.0 57888.88888888889]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 37.55555555555556 40000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [13]:
print(X_train)

[[0.0 0.0 1.0 37.55555555555556 40000.0]
 [0.0 1.0 0.0 40.0 57888.88888888889]
 [1.0 0.0 0.0 48.0 72000.0]
 [0.0 0.0 1.0 38.0 20000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [14]:
print(X_test)

[[0.0 1.0 0.0 15.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


## Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [17]:
print(X_train)

[[0.0 0.0 1.0 -0.39386028623867836 -0.8720378912458752]
 [0.0 1.0 0.0 -0.060593890190565755 0.03302641489811147]
 [1.0 0.0 0.0 1.0300961332396217 0.7469591284402622]
 [0.0 0.0 1.0 -0.3332663960481126 -1.883911028549711]
 [0.0 0.0 1.0 -1.8329651782646204 -0.46728863632434076]
 [1.0 0.0 0.0 1.0300961332396217 1.1011147264966048]
 [0.0 1.0 0.0 1.3027686390971684 1.303489353957372]
 [1.0 0.0 0.0 -0.742275154834433 0.03864793232757714]]


In [18]:
print(X_test)

[[0.0 1.0 0.0 -3.4690002134099016 -0.16372669513319002]
 [1.0 0.0 0.0 -0.46960264897688603 0.4939908441143033]]
